### ISSUE TITLE
Why is QUD_VIRIDIAN different than QUD_COLORS[k]?

### ISSUE THREAD

**Issue by Wreckstation** [TrashMonks/hagadias#71]
## constants.py
```
"k": (15, 59, 58)
...
QUD_VIRIDIAN = (15, 64, 63, 255)
```

## Display.txt
```
"k":"0f3b3a",
...
"camera":{"background":"0f3b3a"}
```

Why? This caused ?say in cryptogull to have the background of "press [space]" to be a slightly different shade because i specified #0f3b3a as a color and the background color of the rest of the image was specified to be QUD_VIRIDIAN.

**Comment by egocarib** [comment]
Perhaps this was simply a typo? It has been set to that value all the way back since the original creation of `qudtile.py`:

https://github.com/TrashMonks/hagadias/blob/b6177d565a580d711c551bac1eba38c83dba5e92/qudtile.py

It was later migrated from `qudtile.py` into `constants.py`, but remained unchanged.

I can't think of any reason it would be set to a slightly different color than what is defined in the game's Display.txt.

**Comment by syntaxaire** [comment]
I think I captured it directly from the running game.
